### ISSUE TITLE
Cluster example file doesn't describe the user directive

### ISSUE THREAD

**Issue by mpiraux** [tbarbette/npf#15]
https://github.com/tbarbette/npf/blob/d098aef870c2dbfcef14b6aafba56fce28180d59/cluster/cluster01.node.sample

Also, the addr directive look like user@domain can be used, although it does not seem to work any more.

**Comment by tbarbette** [comment]
You can find the doc here : https://github.com/tbarbette/npf/tree/d098aef870c2dbfcef14b6aafba56fce28180d59/cluster

If you don't need funny parameters such as the NICs etc, then user@server should be working. I'll look at that.

**Comment by tbarbette** [comment]
Ok got it. Thanks !
