### ISSUE TITLE
Missing config in example scripts and documentation

### ISSUE THREAD

**Issue by kesnar** [tbarbette/npf#28]
Hello, I was reading the docs and I couldn't run any of the provided simple scripts. I then tried to dig into the repository and found that neither the following test could run
`tests/examples/tests-readme.npf`
Giving me the following error, as in the scripts of the documentation:
`This npf script has no default repository`

I found that the tests/examples/math.npf has this particular line of code that actually solves the above error.
```
%config
default_repo=local //No program under test
```

I would propose to include this line to the broken tests and provide some paragraph in the documentation about the local repo.

Thank you.

(I know it is a minor thing, but as someone coming in first contact with your (really interesting) tool, I find the ability to run simple scripts and build knowledge to be useful).

**Comment by tbarbette** [comment]
Hi!

No worries, making the on-boarding as easy as possible is very important !

The examples should give `local` in the command line or reference only tests with `default_repo=local`.

Where is there one of both missing?

Thanks!
Tom
