### ISSUE TITLE
Better output format

### ISSUE THREAD

**Issue by aliireza** [tbarbette/npf#7]
I think it is better to produce a Pandas/Dask data frame rather than CSV files, as they are easier to post-process. 

It seems CSV output cannot have multiple variables in some cases. For instance, the following CSVs have embedded one variable value into the name of the file. 

![image](https://user-images.githubusercontent.com/12845164/81558989-f0094580-938e-11ea-900f-98e369eb40b1.png)

**Comment by tbarbette** [comment]
Since then I added --single-output which is a Panda DF in CSV, so I guess this is solved :)
